#ifndef __HW_CONFIG_H__
#define __HW_CONFIG_H__

#define NC -1

///< LORA RADIO module ESP8266 WEMOS D1 MINI PINOUT
#define RADIO_MOSI_PIN D7 // GPIO13
#define RADIO_MISO_PIN D6 // GPIO12
#define RADIO_SCK_PIN D5 // GPIO14
#define RADIO_NSS_PIN  D8 // GPIO15
#define RADIO_RST_PIN  D3 // GPIO0
#define RADIO_DIO0_PIN D2 // GPIO4

#endif //__HW_CONFIG_H__